version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - shared_network

  mongodb_exporter:
    image: bitnami/mongodb-exporter:latest
    ports:
      - "9216:9216"
    environment:
      - MONGODB_URI=mongodb://mongos:27017/chat  # 连接到mongos
    networks:
      - shared_network

  alertmanager:
    image: prom/alertmanager:latest
    ports:
      - "9093:9093"
    volumes:
      - alertmanager_data:/alertmanager
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    networks:
      - shared_network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3002:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - shared_network

networks:
  shared_network:
    external: true

volumes:
  prometheus_data:
  alertmanager_data:
  grafana_data: