services:
  configsvr:
    image: mongo:latest
    command: ["mongod", "--configsvr", "--replSet", "configReplSet", "--port", "27018", "--bind_ip_all"]
    ports:
      - 27018:27018
    volumes:
      - configsvr_data:/data/configdb
      - ./backup/configsvr:/backup
    networks:
      - shared_network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  shard1:
    image: mongo:latest
    command: ["mongod", "--shardsvr", "--replSet", "shard1ReplSet", "--port", "27019", "--bind_ip_all"]
    ports:
      - 27019:27019
    volumes:
      - shard1_data:/data/db
      - ./backup/shard1:/backup
    networks:
      - shared_network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    
  shard2:
    image: mongo:latest
    command: ["mongod", "--shardsvr", "--replSet", "shard2ReplSet", "--port", "27020", "--bind_ip_all"]
    ports:
      - 27020:27020
    volumes:
      - shard2_data:/data/db
      - ./backup/shard2:/backup
    networks:
      - shared_network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongos:
    image: mongo:latest
    command: ["mongos", "--configdb", "configReplSet/configsvr:27018", "--bind_ip_all", "--port", "27017"]
    ports:
      - 27030:27017
    depends_on:
      - configsvr
      - shard1
      - shard2
    networks:
      - shared_network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  configsvr_data:
  shard1_data:
  shard2_data:

networks:
  shared_network:
    external: true
